import React,{useState} from "react";
import {ActivityIndicator,Pressable,ScrollView,StyleSheet,Text,TextInput,View} from "react-native";
import {ArrowLeft,Sparkles} from "lucide-react-native";
import {endpoints,errMsg,unwrap} from "../api";
import {OMIQORA} from "../theme";
const C=OMIQORA.colors;
export function BudgetPlannerScreen({onBack}:{onBack:()=>void}){
 const[eventType,setEventType]=useState("wedding"),[totalBudget,setTotalBudget]=useState(""),[guestCount,setGuestCount]=useState(""),[city,setCity]=useState("Hyderabad"),[preferences,setPreferences]=useState(""),[result,setResult]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const plan=async()=>{const budget=Number(totalBudget),guests=Number(guestCount);if(!eventType.trim()||!Number.isFinite(budget)||budget<=0||!Number.isFinite(guests)||guests<=0){setError("Enter a valid event type, budget and guest count.");return}setBusy(true);setError("");try{setResult(unwrap(await endpoints.budget({eventType:eventType.trim(),totalBudget:budget,guestCount:guests,city:city.trim()||undefined,preferences:preferences.split(",").map(x=>x.trim()).filter(Boolean)})))}catch(e){setError(errMsg(e))}finally{setBusy(false)}};
 return <ScrollView style={s.page} contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><View style={s.header}><Pressable onPress={onBack}><ArrowLeft size={20} color={C.goldLight}/></Pressable><Text style={s.title}>AI Budget Planner</Text></View><View style={s.hero}><Sparkles size={26} color={C.goldLight}/><Text style={s.heroTitle}>Plan with live OMIQORA intelligence</Text><Text style={s.copy}>Allocations and service recommendations come from the backend budget planner.</Text></View>{[["Event type",eventType,setEventType],["Total budget (₹)",totalBudget,setTotalBudget],["Guest count",guestCount,setGuestCount],["City",city,setCity],["Preferences, comma separated",preferences,setPreferences]].map(([label,value,setter]:any)=><TextInput key={label} style={s.input} placeholder={label} placeholderTextColor={C.mutedSoft} value={value} onChangeText={setter} keyboardType={label.includes("budget")||label.includes("Guest")?"numeric":"default"}/>)}{error?<Text style={s.error}>{error}</Text>:null}<Pressable style={s.button} onPress={plan} disabled={busy}>{busy?<ActivityIndicator color={C.midnight}/>:<Text style={s.buttonText}>Create real budget plan</Text>}</Pressable>{result?<View style={s.result}><Text style={s.resultTitle}>{result.eventType} · ₹{Number(result.totalBudget??0).toLocaleString("en-IN")}</Text><Text style={s.copy}>Budget per person: ₹{Number(result.budgetPerPerson??0).toLocaleString("en-IN")}</Text>{(result.recommendations??[]).map((x:any,i:number)=><View key={`${x.category}-${i}`} style={s.card}><Text style={s.cardTitle}>{x.category}</Text><Text style={s.copy}>₹{Number(x.allocatedBudget??0).toLocaleString("en-IN")} · {x.percentage}%</Text><Text style={s.copy}>{(x.suggestedServices??[]).length} matching live services</Text></View>)}{(result.tips??[]).map((x:any,i:number)=><Text key={i} style={s.tip}>• {String(x)}</Text>)}</View>:null}</ScrollView>
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:C.midnight},content:{padding:20,paddingBottom:70},header:{height:58,flexDirection:"row",alignItems:"center",gap:15},title:{color:C.white,fontSize:21,fontWeight:"900"},hero:{padding:20,borderRadius:22,backgroundColor:C.deepNavy,marginVertical:12},heroTitle:{color:C.white,fontSize:19,fontWeight:"900",marginTop:10},copy:{color:C.muted,lineHeight:20,marginTop:6},input:{height:55,borderRadius:16,borderWidth:1,borderColor:C.border,backgroundColor:C.input,color:C.white,paddingHorizontal:15,marginBottom:11},error:{color:C.danger,marginVertical:7},button:{height:56,borderRadius:17,backgroundColor:C.gold,alignItems:"center",justifyContent:"center"},buttonText:{color:C.midnight,fontWeight:"900"},result:{marginTop:20},resultTitle:{color:C.white,fontSize:19,fontWeight:"900"},card:{padding:15,borderRadius:16,borderWidth:1,borderColor:C.border,backgroundColor:C.royalNavy,marginTop:10},cardTitle:{color:C.goldLight,fontWeight:"900",textTransform:"capitalize"},tip:{color:C.text,lineHeight:20,marginTop:8}});