import React,{useCallback,useEffect,useState} from "react";
import {ActivityIndicator,FlatList,Pressable,StyleSheet,Text,View} from "react-native";
import {ArrowLeft,MessageCircle,RefreshCw} from "lucide-react-native";
import {endpoints,errMsg,listOf} from "../api";
import {OMIQORA} from "../theme";
const C=OMIQORA.colors;
const nameOf=(x:any)=>[x?.otherUser?.firstName,x?.otherUser?.lastName].filter(Boolean).join(" ")||x?.otherUser?.vendorProfile?.businessName||x?.serviceId?.name||"Service conversation";
const when=(v:any)=>v?new Date(v).toLocaleString("en-IN",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"}):"";
export function ConversationsScreen({onBack,onOpen}:{onBack:()=>void;onOpen:(id:string)=>void}){
 const [items,setItems]=useState<any[]>([]),[busy,setBusy]=useState(true),[error,setError]=useState("");
 const load=useCallback(async()=>{setBusy(true);setError("");try{setItems(listOf(await endpoints.conversations()))}catch(e){setError(errMsg(e))}finally{setBusy(false)}},[]);
 useEffect(()=>{load()},[load]);
 return <View style={s.page}><View style={s.header}><Pressable onPress={onBack} style={s.icon}><ArrowLeft size={20} color={C.goldLight}/></Pressable><View style={{flex:1}}><Text style={s.eye}>SERVICE CONVERSATIONS</Text><Text style={s.title}>Messages</Text></View></View>
 {busy?<View style={s.center}><ActivityIndicator color={C.gold}/></View>:error?<View style={s.center}><Text style={s.error}>{error}</Text><Pressable onPress={load} style={s.retry}><RefreshCw size={16} color={C.midnight}/><Text style={s.retryText}>Try again</Text></Pressable></View>:<FlatList data={items} keyExtractor={(x,i)=>String(x?.conversationId??x?._id??x?.id??i)} contentContainerStyle={s.list} ListEmptyComponent={<View style={s.center}><MessageCircle size={30} color={C.gold}/><Text style={s.empty}>No conversations yet</Text><Text style={s.hint}>Open a booking and tap Message to start a service conversation.</Text></View>} renderItem={({item})=>{const id=String(item?.conversationId??item?._id??item?.id??"");const unread=Number(item?.unreadCount??0);return <Pressable style={s.card} onPress={()=>id?onOpen(id):undefined}><View style={s.avatar}><MessageCircle size={20} color={C.midnight}/></View><View style={{flex:1}}><View style={s.row}><Text numberOfLines={1} style={s.name}>{nameOf(item)}</Text><Text style={s.time}>{when(item?.lastMessageAt)}</Text></View><Text numberOfLines={1} style={s.service}>{item?.serviceId?.name??"OMIQORA service"}</Text><Text numberOfLines={2} style={s.copy}>{item?.lastMessage||"Open conversation"}</Text></View>{unread>0?<View style={s.badge}><Text style={s.badgeText}>{unread>99?"99+":unread}</Text></View>:null}</Pressable>}}/>}
 </View>
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:C.midnight},header:{padding:18,flexDirection:"row",alignItems:"center",gap:12,borderBottomWidth:1,borderBottomColor:C.border},icon:{width:42,height:42,borderRadius:14,borderWidth:1,borderColor:C.border,backgroundColor:C.royalNavy,alignItems:"center",justifyContent:"center"},eye:{color:C.gold,fontSize:8,fontWeight:"900",letterSpacing:1.2},title:{color:C.white,fontSize:21,fontWeight:"900",marginTop:3},list:{padding:16,gap:10,flexGrow:1},card:{borderRadius:19,borderWidth:1,borderColor:C.border,backgroundColor:C.royalNavy,padding:14,flexDirection:"row",alignItems:"center",gap:12},avatar:{width:46,height:46,borderRadius:16,backgroundColor:C.gold,alignItems:"center",justifyContent:"center"},row:{flexDirection:"row",justifyContent:"space-between",gap:8},name:{color:C.white,fontSize:13,fontWeight:"900",flex:1},time:{color:C.mutedSoft,fontSize:9},service:{color:C.goldLight,fontSize:10,fontWeight:"700",marginTop:3},copy:{color:C.muted,fontSize:10,lineHeight:16,marginTop:4},badge:{minWidth:24,height:24,borderRadius:12,backgroundColor:C.gold,alignItems:"center",justifyContent:"center",paddingHorizontal:6},badgeText:{color:C.midnight,fontSize:9,fontWeight:"900"},center:{flex:1,minHeight:280,alignItems:"center",justifyContent:"center",padding:30},empty:{color:C.white,fontWeight:"900",fontSize:14,marginTop:12},hint:{color:C.muted,fontSize:10,lineHeight:17,textAlign:"center",marginTop:7},error:{color:C.danger,textAlign:"center",fontSize:12},retry:{marginTop:14,height:43,borderRadius:14,backgroundColor:C.gold,paddingHorizontal:16,flexDirection:"row",alignItems:"center",gap:7},retryText:{color:C.midnight,fontWeight:"900",fontSize:11}});
