import React,{useCallback,useEffect,useMemo,useState} from "react";
import {ActivityIndicator,Alert,Modal,Pressable,RefreshControl,ScrollView,StyleSheet,Text,TextInput,View} from "react-native";
import {BarChart3,BriefcaseBusiness,CalendarDays,CreditCard,FileCheck2,MessageCircle,Plus,RefreshCw,ShieldCheck,Star,Store,Tag,Users,X} from "lucide-react-native";
import {endpoints,errMsg,listOf,unwrap} from "../api";
import {useSession} from "../stores/session";
import {OMIQORA} from "../theme";
const C=OMIQORA.colors;
const idOf=(x:any)=>String(x?._id??x?.id??"");
const money=(v:any)=>`₹${Number(v??0).toLocaleString("en-IN",{maximumFractionDigits:2})}`;
const pretty=(v:any)=>String(v??"—").replaceAll("_"," ");
type Mode="admin"|"vendor"|"customer";
type Dialog={kind:string;item?:any}|null;

export function OperationsScreen({mode,onOpenBooking,onOpenService,onMessages}:{mode:Mode;onOpenBooking?:(id:string)=>void;onOpenService?:(id:string)=>void;onMessages?:()=>void}){
 const user=useSession(x=>x.user); const [tab,setTab]=useState(""); const [data,setData]=useState<Record<string,any>>({}); const [busy,setBusy]=useState(true); const [refreshing,setRefreshing]=useState(false); const [error,setError]=useState(""); const [dialog,setDialog]=useState<Dialog>(null); const [form,setForm]=useState<Record<string,string>>({}); const [saving,setSaving]=useState(false);
 const tabs=useMemo(()=>mode==="admin"?["Overview","Users","Vendors","Services","Bookings","Payments","Categories","Analytics"]:mode==="vendor"?["Overview","Services","Bookings","Earnings","Reviews","Verification"]:["Bookings","Payments","Reviews","Saved","Support"],[mode]);
 useEffect(()=>{if(!tab)setTab(tabs[0])},[tabs,tab]);
 const load=useCallback(async()=>{setError("");try{if(mode==="admin"){const [overview,users,vendors,services,bookings,payments,categories,revenue,growth,topCategories,topVendors,distribution]=await Promise.all([endpoints.adminOverview(),endpoints.adminUsers({page:1,limit:100}),endpoints.adminVendorApplications(),endpoints.adminServices(),endpoints.adminBookings(),endpoints.adminPaymentList(),endpoints.categories(),endpoints.adminRevenueChart(),endpoints.adminUserGrowth(),endpoints.adminTopCategories(),endpoints.adminTopVendors(),endpoints.adminBookingDistribution()]);setData({overview:unwrap(overview),users:listOf(users),vendors:listOf(vendors),services:listOf(services),bookings:listOf(bookings),payments:listOf(payments),categories:listOf(categories),revenue:unwrap(revenue),growth:unwrap(growth),topCategories:unwrap(topCategories),topVendors:unwrap(topVendors),distribution:unwrap(distribution)});}else if(mode==="vendor"){const [overview,services,bookings,payments,application,readiness,revenue,performance]=await Promise.all([endpoints.vendorOverview(),endpoints.myServices(),endpoints.vendorBookings(),endpoints.payments(),endpoints.vendorApplication().catch(()=>null),endpoints.vendorReadiness().catch(()=>null),endpoints.vendorRevenueChart(),endpoints.vendorServicePerformance()]);const vendorId=String(user?._id??user?.id??"");const reviews=vendorId?await endpoints.vendorReviews(vendorId).catch(()=>null):null;setData({overview:unwrap(overview),services:listOf(services),bookings:listOf(bookings),payments:listOf(payments),application:unwrap(application),readiness:unwrap(readiness),revenue:unwrap(revenue),performance:unwrap(performance),reviews:listOf(reviews)});}else{const [bookings,payments,reviews,saved]=await Promise.all([endpoints.bookings(),endpoints.payments(),endpoints.myReviews(),endpoints.saved()]);setData({bookings:listOf(bookings),payments:listOf(payments),reviews:listOf(reviews),saved:listOf(saved)});}}catch(e){setError(errMsg(e));}finally{setBusy(false);setRefreshing(false)}},[mode,user?._id,user?.id]);
 useEffect(()=>{void load()},[load]);
 const act=async(fn:()=>Promise<any>,success:string)=>{setSaving(true);try{await fn();setDialog(null);setForm({});Alert.alert("OMIQORA",success);await load()}catch(e){Alert.alert("Operation failed",errMsg(e))}finally{setSaving(false)}};
 const open=(kind:string,item?:any,seed:Record<string,string>={})=>{setForm(seed);setDialog({kind,item})};
 if(busy)return <View style={s.center}><ActivityIndicator color={C.gold}/></View>;
 const section=()=>{
  if(mode==="admin")return adminView(tab,data,open,onOpenBooking,onOpenService);
  if(mode==="vendor")return vendorView(tab,data,open,onOpenBooking,onOpenService);
  return customerView(tab,data,open,onOpenBooking,onOpenService,onMessages);
 };
 return <View style={s.page}><ScrollView contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>{setRefreshing(true);void load()}} tintColor={C.gold}/>}><View style={s.hero}>{mode==="admin"?<ShieldCheck size={26} color={C.goldLight}/>:mode==="vendor"?<BriefcaseBusiness size={26} color={C.goldLight}/>:<FileCheck2 size={26} color={C.goldLight}/>}<Text style={s.title}>{mode==="admin"?"Platform operations":mode==="vendor"?"Vendor operations":"My OMIQORA"}</Text><Text style={s.copy}>Live production-backed controls. No demo balances, fake orders, or hardcoded marketplace records.</Text></View>{error?<View style={s.errorCard}><Text style={s.error}>{error}</Text><Pressable style={s.primary} onPress={()=>void load()}><RefreshCw size={16} color={C.midnight}/><Text style={s.primaryText}>Retry</Text></Pressable></View>:null}<ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.tabs}>{tabs.map(x=><Pressable key={x} style={[s.tab,tab===x&&s.tabOn]} onPress={()=>setTab(x)}><Text style={[s.tabText,tab===x&&s.tabTextOn]}>{x}</Text></Pressable>)}</ScrollView>{section()}</ScrollView><Editor dialog={dialog} form={form} setForm={setForm} saving={saving} close={()=>setDialog(null)} act={act}/></View>;
}

function adminView(tab:string,d:any,open:any,onBooking?:any,onService?:any){
 if(tab==="Overview")return <><Metrics value={d.overview}/><Quick rows={[['Users',d.users?.length,Users],['Vendor applications',d.vendors?.length,ShieldCheck],['Services',d.services?.length,Store],['Bookings',d.bookings?.length,CalendarDays],['Payments',d.payments?.length,CreditCard],['Categories',d.categories?.length,Tag]]}/></>;
 if(tab==="Users")return <List items={d.users} empty="No users" render={(x:any)=><Card key={idOf(x)} title={`${x.firstName??''} ${x.lastName??''}`.trim()||x.email} sub={`${x.email??''} · ${pretty(x.role)} · ${pretty(x.status)}`} actions={<><Small label="Active" onPress={()=>open('user-status',x,{status:'active'})}/><Small label="Suspend" danger onPress={()=>open('user-status',x,{status:'suspended'})}/></>}/>}/>;
 if(tab==="Vendors")return <List items={d.vendors} empty="No vendor applications" render={(x:any)=><Card key={idOf(x)} title={x.businessName??x.vendorType??'Vendor application'} sub={`${pretty(x.status)} · ${x.city??''} ${x.state??''}`} body={`PAN: ${x.panNumber?'submitted':'missing'} · Documents: ${x.documents?.length??0} · Portfolio: ${x.portfolioLinks?.length??0}`} actions={<><Small label="Approve" onPress={()=>open('vendor-approve',x)}/><Small label="Reject" danger onPress={()=>open('vendor-reject',x,{reason:''})}/></>}/>}/>;
 if(tab==="Services")return <List items={d.services} empty="No services" render={(x:any)=><Card key={idOf(x)} title={x.name??'Service'} sub={`${money(x.basePrice)} · ${pretty(x.priceType)} · ${pretty(x.status)}`} body={`${x.location?.city??''} · Rating ${x.rating??0} · ${x.bookingCount??0} bookings`} onPress={onService?()=>onService(idOf(x)):undefined} actions={<><Small label="Approve" onPress={()=>open('service-approve',x)}/><Small label="Reject" danger onPress={()=>open('service-reject',x,{reason:''})}/></>}/>}/>;
 if(tab==="Bookings")return <List items={d.bookings} empty="No bookings" render={(x:any)=><Card key={idOf(x)} title={x.bookingNumber??'Booking'} sub={`${pretty(x.status)} · ${money(x.totalAmount)}`} body={`${x.serviceId?.name??'Service'} · ${x.startDate?new Date(x.startDate).toLocaleDateString('en-IN'):''}${x.endDate?' → '+new Date(x.endDate).toLocaleDateString('en-IN'):''}`} onPress={onBooking?()=>onBooking(idOf(x)):undefined}/>}/>;
 if(tab==="Payments")return <List items={d.payments} empty="No payments" render={(x:any)=><Card key={idOf(x)} title={money(x.amount)} sub={`${pretty(x.status)} · ${pretty(x.paymentMethod??'Razorpay')}`} body={`${x.bookingId?.bookingNumber??'Booking'} · ${x.createdAt?new Date(x.createdAt).toLocaleString('en-IN'):''}`} actions={<Small label="Refund" danger onPress={()=>open('refund',x,{reason:''})}/>}/>}/>;
 if(tab==="Categories")return <><Pressable style={s.primary} onPress={()=>open('category-create',null,{name:'',icon:'',description:''})}><Plus size={16} color={C.midnight}/><Text style={s.primaryText}>Add category</Text></Pressable><List items={d.categories} empty="No categories" render={(x:any)=><Card key={idOf(x)} title={`${x.icon??'📦'} ${x.name??'Category'}`} sub={`${x.serviceCount??0} services`} body={x.description} actions={<><Small label="Edit" onPress={()=>open('category-edit',x,{name:x.name??'',icon:x.icon??'',description:x.description??''})}/><Small label="Deactivate" danger onPress={()=>open('category-delete',x)}/></>}/>}/></>;
 return <><Text style={s.section}>LIVE ANALYTICS CONTRACTS</Text><DataBlock title="Revenue" value={d.revenue}/><DataBlock title="User growth" value={d.growth}/><DataBlock title="Top categories" value={d.topCategories}/><DataBlock title="Top vendors" value={d.topVendors}/><DataBlock title="Booking distribution" value={d.distribution}/></>;
}
function vendorView(tab:string,d:any,open:any,onBooking?:any,onService?:any){
 if(tab==="Overview")return <><Metrics value={d.overview}/><DataBlock title="Service performance" value={d.performance}/></>;
 if(tab==="Services")return <><Pressable style={s.primary} onPress={()=>open('service-create',null,{name:'',description:'',categoryId:'',basePrice:'',priceType:'fixed',city:'',state:'',serviceRadius:'25'})}><Plus size={16} color={C.midnight}/><Text style={s.primaryText}>Add service</Text></Pressable><List items={d.services} empty="No services" render={(x:any)=><Card key={idOf(x)} title={x.name} sub={`${money(x.basePrice)} · ${pretty(x.status)}`} body={`${x.location?.city??''} · ${x.bookingCount??0} bookings · rating ${x.rating??0}`} onPress={onService?()=>onService(idOf(x)):undefined} actions={<><Small label="Edit" onPress={()=>open('service-edit',x,{name:x.name??'',description:x.description??'',categoryId:idOf(x.categoryId),basePrice:String(x.basePrice??''),priceType:x.priceType??'fixed',city:x.location?.city??'',state:x.location?.state??'',serviceRadius:String(x.location?.serviceRadius??25)})}/><Small label="Delete" danger onPress={()=>open('service-delete',x)}/></>}/>}/></>;
 if(tab==="Bookings")return <List items={d.bookings} empty="No bookings" render={(x:any)=><Card key={idOf(x)} title={x.bookingNumber??'Booking'} sub={`${pretty(x.status)} · ${money(x.totalAmount)}`} body={x.serviceId?.name??'Service'} onPress={onBooking?()=>onBooking(idOf(x)):undefined} actions={<><Small label="Confirm" onPress={()=>open('booking-status',x,{status:'confirmed'})}/><Small label="Start" onPress={()=>open('booking-status',x,{status:'in_progress'})}/><Small label="Complete" onPress={()=>open('booking-status',x,{status:'completed'})}/></>}/>}/>;
 if(tab==="Earnings")return <><Metrics value={d.overview}/><List items={d.payments} empty="No payment records" render={(x:any)=><Card key={idOf(x)} title={money(x.vendorPayoutAmount??x.amount)} sub={`${pretty(x.status)} · ${x.bookingId?.bookingNumber??'Booking'}`} body={x.createdAt?new Date(x.createdAt).toLocaleString('en-IN'):''}/>}/><DataBlock title="Revenue trend" value={d.revenue}/></>;
 if(tab==="Reviews")return <List items={d.reviews} empty="No reviews" render={(x:any)=><Card key={idOf(x)} title={`${x.rating??0}/5 · ${x.serviceId?.name??'Service'}`} sub={x.customerId?.firstName??'Customer'} body={x.comment} actions={<Small label={x.vendorReply?'Update reply':'Reply'} onPress={()=>open('review-reply',x,{reply:x.vendorReply??''})}/>}/>}/>;
 return <><DataBlock title="Vendor readiness" value={d.readiness}/><DataBlock title="Vendor application" value={d.application}/><Text style={s.note}>Document upload and resubmission remain in the existing Vendor verification screen from Account. This operations view shows the live readiness/application contract.</Text></>;
}
function customerView(tab:string,d:any,open:any,onBooking?:any,onService?:any,onMessages?:any){
 if(tab==="Bookings")return <List items={d.bookings} empty="No bookings" render={(x:any)=><Card key={idOf(x)} title={x.bookingNumber??'Booking'} sub={`${pretty(x.status)} · ${money(x.totalAmount)}`} body={`${x.serviceId?.name??'Service'} · ${x.startDate?new Date(x.startDate).toLocaleDateString('en-IN'):''}${x.endDate?' → '+new Date(x.endDate).toLocaleDateString('en-IN'):''}`} onPress={onBooking?()=>onBooking(idOf(x)):undefined}/>}/>;
 if(tab==="Payments")return <List items={d.payments} empty="No payments" render={(x:any)=><Card key={idOf(x)} title={money(x.amount)} sub={`${pretty(x.status)} · ${x.bookingId?.bookingNumber??'Booking'}`} body={x.createdAt?new Date(x.createdAt).toLocaleString('en-IN'):''}/>}/>;
 if(tab==="Reviews")return <List items={d.reviews} empty="No reviews" render={(x:any)=><Card key={idOf(x)} title={`${x.rating??0}/5 · ${x.serviceId?.name??'Service'}`} sub={pretty(x.status)} body={x.comment} actions={<Small label="Delete" danger onPress={()=>open('review-delete',x)}/>}/>}/>;
 if(tab==="Saved")return <List items={d.saved} empty="No saved services" render={(x:any)=><Card key={idOf(x)} title={x.name??'Service'} sub={`${money(x.basePrice)} · rating ${x.rating??0}`} body={x.location?.city??''} onPress={onService?()=>onService(idOf(x)):undefined}/>}/>;
 return <View style={s.card}><MessageCircle size={22} color={C.gold}/><Text style={s.cardTitle}>Help & support</Text><Text style={s.cardBody}>Use OMI for AI-assisted support or open your real conversations. Refund status is shown from payment records; OMIQORA does not display fake wallet credits, coupons, invoices, or refund approvals without backend records.</Text>{onMessages?<Pressable style={s.primary} onPress={onMessages}><Text style={s.primaryText}>Open messages</Text></Pressable>:null}</View>;
}

function Editor({dialog,form,setForm,saving,close,act}:{dialog:Dialog;form:Record<string,string>;setForm:any;saving:boolean;close:()=>void;act:(fn:()=>Promise<any>,success:string)=>void}){if(!dialog)return null;const k=dialog.kind,x=dialog.item;const field=(name:string,label:string,keyboardType:any='default')=><TextInput style={s.input} value={form[name]??''} onChangeText={v=>setForm((p:any)=>({...p,[name]:v}))} placeholder={label} placeholderTextColor={C.mutedSoft} keyboardType={keyboardType} multiline={name==='description'||name==='reason'||name==='reply'}/>;let title=k.replaceAll('-',' '),fields:React.ReactNode=null,run:()=>Promise<any>=async()=>{},success='Completed';
 if(k==='user-status'){fields=field('status','Status');run=()=>endpoints.adminUserStatus(idOf(x),form.status);success='User status updated'}
 else if(k==='vendor-approve'){run=()=>endpoints.adminApproveVendor(idOf(x));success='Vendor approved'}
 else if(k==='vendor-reject'){fields=field('reason','Rejection reason');run=()=>endpoints.adminRejectVendor(idOf(x),{reason:form.reason});success='Vendor rejected'}
 else if(k==='service-approve'){run=()=>endpoints.adminApproveService(idOf(x));success='Service approved'}
 else if(k==='service-reject'){fields=field('reason','Rejection reason');run=()=>endpoints.adminRejectService(idOf(x),form.reason);success='Service rejected'}
 else if(k==='refund'){fields=field('reason','Refund reason');run=()=>endpoints.adminRefund(idOf(x),form.reason);success='Refund processed through payment contract'}
 else if(k==='category-create'||k==='category-edit'){fields=<>{field('name','Name')}{field('icon','Icon / emoji')}{field('description','Description')}</>;run=()=>k==='category-create'?endpoints.createCategory(form):endpoints.updateCategory(idOf(x),form);success=k==='category-create'?'Category created':'Category updated'}
 else if(k==='category-delete'){run=()=>endpoints.deleteCategory(idOf(x));success='Category deactivated'}
 else if(k==='service-create'||k==='service-edit'){fields=<>{field('name','Service name')}{field('description','Description')}{field('categoryId','Category ID')}{field('basePrice','Base price','numeric')}{field('priceType','Price type: fixed / per_day / per_hour / per_event')}{field('city','City')}{field('state','State')}{field('serviceRadius','Service radius km','numeric')}</>;const payload=()=>({name:form.name.trim(),description:form.description.trim(),categoryId:form.categoryId.trim(),basePrice:Number(form.basePrice),priceType:form.priceType.trim(),location:{city:form.city.trim(),state:form.state.trim(),serviceRadius:Number(form.serviceRadius||25)}});run=()=>k==='service-create'?endpoints.createService(payload()):endpoints.updateService(idOf(x),payload());success=k==='service-create'?'Service created':'Service updated'}
 else if(k==='service-delete'){run=()=>endpoints.deleteService(idOf(x));success='Service deleted'}
 else if(k==='booking-status'){fields=field('status','Booking status');run=()=>endpoints.updateBookingStatus(idOf(x),form.status);success='Booking status updated'}
 else if(k==='review-reply'){fields=field('reply','Vendor reply');run=()=>endpoints.replyReview(idOf(x),form.reply);success='Review reply saved'}
 else if(k==='review-delete'){run=()=>endpoints.deleteReview(idOf(x));success='Review deleted'}
 return <Modal visible transparent animationType="slide" onRequestClose={close}><View style={s.modalShade}><View style={s.modal}><View style={s.modalHead}><Text style={s.modalTitle}>{title.toUpperCase()}</Text><Pressable onPress={close}><X size={20} color={C.gold}/></Pressable></View>{fields}<Pressable style={s.primary} disabled={saving} onPress={()=>void act(run,success)}>{saving?<ActivityIndicator color={C.midnight}/>:<Text style={s.primaryText}>Confirm</Text>}</Pressable></View></View></Modal>}
function Metrics({value}:{value:any}){const rows=Object.entries(value??{}).filter(([,v])=>typeof v==='number').slice(0,12);return <><Text style={s.section}>LIVE OVERVIEW</Text><View style={s.grid}>{rows.map(([k,v])=><View style={s.metric} key={k}><Text style={s.metricValue}>{/amount|revenue|earning|spent|payout/i.test(k)?money(v):Number(v).toLocaleString('en-IN',{maximumFractionDigits:2})}</Text><Text style={s.metricLabel}>{pretty(k)}</Text></View>)}</View></>}
function Quick({rows}:{rows:any[]}){return <><Text style={s.section}>OPERATIONS INVENTORY</Text><View style={s.grid}>{rows.map(([name,count,Icon])=><View style={s.metric} key={name}><Icon size={18} color={C.gold}/><Text style={s.metricValue}>{Number(count??0).toLocaleString('en-IN')}</Text><Text style={s.metricLabel}>{name}</Text></View>)}</View></>}
function List({items,empty,render}:{items:any[];empty:string;render:(x:any)=>React.ReactNode}){return <>{!items?.length?<Text style={s.empty}>{empty}</Text>:items.map(render)}</>}
function Card({title,sub,body,actions,onPress}:{title:string;sub?:string;body?:string;actions?:React.ReactNode;onPress?:()=>void}){return <Pressable style={s.card} onPress={onPress}><Text style={s.cardTitle}>{title}</Text>{sub?<Text style={s.cardSub}>{sub}</Text>:null}{body?<Text style={s.cardBody}>{body}</Text>:null}{actions?<View style={s.actions}>{actions}</View>:null}</Pressable>}
function Small({label,onPress,danger=false}:{label:string;onPress:()=>void;danger?:boolean}){return <Pressable style={[s.small,danger&&s.smallDanger]} onPress={onPress}><Text style={[s.smallText,danger&&s.danger]}>{label}</Text></Pressable>}
function DataBlock({title,value}:{title:string;value:any}){const text=Array.isArray(value)?value.slice(0,8).map((x:any)=>Object.entries(x??{}).slice(0,4).map(([k,v])=>`${pretty(k)}: ${typeof v==='object'?'…':String(v)}`).join(' · ')).join('\n'):Object.entries(value??{}).slice(0,12).map(([k,v])=>`${pretty(k)}: ${typeof v==='object'?'…':String(v)}`).join('\n');return <View style={s.card}><BarChart3 size={20} color={C.gold}/><Text style={s.cardTitle}>{title}</Text><Text style={s.cardBody}>{text||'No data returned'}</Text></View>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:C.midnight},content:{padding:18,paddingBottom:40},center:{flex:1,backgroundColor:C.midnight,alignItems:'center',justifyContent:'center'},hero:{borderRadius:24,borderWidth:1,borderColor:C.borderStrong,backgroundColor:C.royalNavy,padding:19},title:{color:C.white,fontSize:23,fontWeight:'900',marginTop:10},copy:{color:C.muted,fontSize:11,lineHeight:18,marginTop:7},tabs:{gap:8,paddingVertical:16},tab:{height:40,borderRadius:14,borderWidth:1,borderColor:C.border,paddingHorizontal:14,alignItems:'center',justifyContent:'center',backgroundColor:C.royalNavy},tabOn:{backgroundColor:C.gold,borderColor:C.gold},tabText:{color:C.muted,fontSize:10,fontWeight:'800'},tabTextOn:{color:C.midnight},section:{color:C.gold,fontSize:9,fontWeight:'900',letterSpacing:1.4,marginTop:12,marginBottom:10},grid:{flexDirection:'row',flexWrap:'wrap',gap:9},metric:{width:'48%',minHeight:98,borderRadius:18,borderWidth:1,borderColor:C.border,backgroundColor:C.royalNavy,padding:14},metricValue:{color:C.white,fontSize:18,fontWeight:'900',marginTop:7},metricLabel:{color:C.muted,fontSize:9,marginTop:5,textTransform:'capitalize'},card:{borderRadius:19,borderWidth:1,borderColor:C.border,backgroundColor:C.royalNavy,padding:16,marginBottom:10},cardTitle:{color:C.white,fontSize:14,fontWeight:'900',marginTop:5},cardSub:{color:C.goldLight,fontSize:10,fontWeight:'800',marginTop:6,textTransform:'capitalize'},cardBody:{color:C.muted,fontSize:10,lineHeight:17,marginTop:7},actions:{flexDirection:'row',flexWrap:'wrap',gap:7,marginTop:12},small:{minHeight:36,borderRadius:12,borderWidth:1,borderColor:C.borderStrong,paddingHorizontal:12,alignItems:'center',justifyContent:'center'},smallDanger:{borderColor:C.dangerBorder},smallText:{color:C.goldLight,fontSize:9,fontWeight:'900'},danger:{color:C.danger},primary:{minHeight:48,borderRadius:15,backgroundColor:C.gold,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8,paddingHorizontal:15,marginVertical:8},primaryText:{color:C.midnight,fontSize:10,fontWeight:'900'},errorCard:{borderRadius:18,borderWidth:1,borderColor:C.dangerBorder,padding:14,marginTop:12},error:{color:C.danger,fontSize:10,lineHeight:16},empty:{color:C.muted,textAlign:'center',padding:30},note:{color:C.muted,fontSize:10,lineHeight:17,marginTop:12},modalShade:{flex:1,backgroundColor:'rgba(0,0,0,0.72)',justifyContent:'flex-end'},modal:{maxHeight:'85%',backgroundColor:C.deepNavy,borderTopLeftRadius:28,borderTopRightRadius:28,borderWidth:1,borderColor:C.borderStrong,padding:20},modalHead:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:14},modalTitle:{color:C.white,fontSize:15,fontWeight:'900'},input:{minHeight:50,maxHeight:110,borderRadius:15,borderWidth:1,borderColor:C.border,backgroundColor:C.input,color:C.white,paddingHorizontal:14,paddingVertical:10,fontSize:11,marginBottom:9}});
