import React,{useCallback,useEffect,useState} from "react";
import {ActivityIndicator,Pressable,ScrollView,StyleSheet,Text,View} from "react-native";
import {ArrowLeft,CreditCard,ReceiptText,RefreshCw} from "lucide-react-native";
import {endpoints,errMsg,unwrap} from "../api";
import {OMIQORA} from "../theme";
const C=OMIQORA.colors; const money=(v:any)=>`₹${Number(v??0).toLocaleString("en-IN",{maximumFractionDigits:2})}`;
const Row=({label,value}:{label:string;value:any})=><View style={s.row}><Text style={s.label}>{label}</Text><Text selectable style={s.value}>{value||"—"}</Text></View>;
export function PaymentDetailScreen({paymentId,onBack}:{paymentId:string;onBack:()=>void}){
 const[payment,setPayment]=useState<any>(null),[busy,setBusy]=useState(true),[error,setError]=useState("");
 const load=useCallback(async()=>{setBusy(true);setError("");try{setPayment(unwrap(await endpoints.payment(paymentId)))}catch(e){setError(errMsg(e))}finally{setBusy(false)}},[paymentId]);useEffect(()=>{load()},[load]);
 return <View style={s.page}><View style={s.header}><Pressable style={s.icon} onPress={onBack}><ArrowLeft size={20} color={C.gold}/></Pressable><Text style={s.title}>Payment details</Text><Pressable style={s.icon} onPress={load}><RefreshCw size={18} color={C.gold}/></Pressable></View>
 {busy?<View style={s.center}><ActivityIndicator color={C.gold}/></View>:error?<View style={s.center}><Text style={s.error}>{error}</Text></View>:<ScrollView contentContainerStyle={s.content}><View style={s.hero}><CreditCard size={25} color={C.goldLight}/><Text style={s.amount}>{money(payment?.amount)}</Text><Text style={s.status}>{String(payment?.status??"pending").toUpperCase()}</Text></View><Text style={s.section}>TRANSACTION</Text><View style={s.card}><Row label="Service" value={payment?.bookingId?.serviceId?.name}/><Row label="Booking" value={payment?.bookingId?.bookingNumber}/><Row label="Paid / created" value={payment?.createdAt?new Date(payment.createdAt).toLocaleString("en-IN"):"—"}/><Row label="Payment ID" value={payment?.razorpayPaymentId??payment?.transactionId}/><Row label="Order ID" value={payment?.razorpayOrderId}/><Row label="Currency" value={payment?.currency}/></View><Text style={s.section}>BREAKDOWN</Text><View style={s.card}><Row label="Total" value={money(payment?.amount)}/><Row label="Platform commission" value={money(payment?.commissionAmount)}/><Row label="Vendor earning" value={money(payment?.vendorPayoutAmount)}/><Row label="Payout status" value={String(payment?.payoutStatus??"pending").toUpperCase()}/>{Number(payment?.refundAmount)>0?<Row label="Refunded" value={money(payment.refundAmount)}/>:null}</View><View style={s.pass}><ReceiptText size={22} color={C.goldLight}/><View style={{flex:1}}><Text style={s.passTitle}>OMIQORA service record</Text><Text style={s.passCopy}>This transaction stays linked to its booking and service history.</Text></View></View></ScrollView>}</View>
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:C.midnight},header:{height:64,flexDirection:"row",alignItems:"center",justifyContent:"space-between",paddingHorizontal:18,borderBottomWidth:1,borderBottomColor:C.border},icon:{width:42,height:42,borderRadius:21,alignItems:"center",justifyContent:"center",backgroundColor:C.royalNavy,borderWidth:1,borderColor:C.border},title:{color:C.white,fontSize:19,fontWeight:"900"},center:{flex:1,alignItems:"center",justifyContent:"center",padding:24},content:{padding:20,paddingBottom:40},hero:{borderRadius:24,borderWidth:1,borderColor:C.borderStrong,backgroundColor:C.royalNavy,padding:22,alignItems:"center"},amount:{color:C.white,fontSize:30,fontWeight:"900",marginTop:12},status:{color:C.goldLight,fontSize:10,fontWeight:"900",letterSpacing:1.5,marginTop:8},section:{color:C.gold,fontSize:9,fontWeight:"900",letterSpacing:1.6,marginTop:24,marginBottom:9},card:{borderRadius:20,borderWidth:1,borderColor:C.border,backgroundColor:C.royalNavy,paddingHorizontal:16},row:{paddingVertical:14,borderBottomWidth:1,borderBottomColor:C.border},label:{color:C.muted,fontSize:10},value:{color:C.white,fontSize:12,fontWeight:"700",marginTop:5},pass:{marginTop:18,borderRadius:20,borderWidth:1,borderColor:C.borderStrong,padding:16,flexDirection:"row",gap:12,alignItems:"center"},passTitle:{color:C.white,fontWeight:"900"},passCopy:{color:C.muted,fontSize:10,lineHeight:16,marginTop:4},error:{color:C.danger,textAlign:"center"}});
