import React,{useState} from "react";
import {ActivityIndicator,Alert,Pressable,StyleSheet,Text,TextInput,View} from "react-native";
import {ArrowLeft,Star} from "lucide-react-native";
import {endpoints,errMsg} from "../api";
import {OMIQORA} from "../theme";
const C=OMIQORA.colors;
export function ReviewScreen({bookingId,onBack,onDone}:{bookingId:string;onBack:()=>void;onDone:()=>void}){
 const [rating,setRating]=useState(5),[comment,setComment]=useState(""),[busy,setBusy]=useState(false);
 const submit=async()=>{const value=comment.trim();if(value.length<10){Alert.alert("Review","Please write at least 10 characters.");return}setBusy(true);try{await endpoints.createReview({bookingId,rating,comment:value});Alert.alert("Thank you","Your verified booking review was submitted.");onDone()}catch(e){Alert.alert("Unable to submit review",errMsg(e))}finally{setBusy(false)}};
 return <View style={s.page}><View style={s.header}><Pressable onPress={onBack} style={s.icon}><ArrowLeft size={20} color={C.gold}/></Pressable><Text style={s.title}>Review service</Text><View style={s.icon}/></View><View style={s.content}><Text style={s.eye}>VERIFIED BOOKING REVIEW</Text><Text style={s.head}>How was your experience?</Text><View style={s.stars}>{[1,2,3,4,5].map(value=><Pressable key={value} onPress={()=>setRating(value)}><Star size={34} color={C.goldLight} fill={value<=rating?C.goldLight:"transparent"}/></Pressable>)}</View><TextInput value={comment} onChangeText={setComment} placeholder="Share useful details about the service..." placeholderTextColor={C.mutedSoft} style={s.input} multiline maxLength={1000}/><Text style={s.count}>{comment.length}/1000</Text><Pressable style={s.cta} onPress={submit} disabled={busy}>{busy?<ActivityIndicator color={C.midnight}/>:<Text style={s.ctaText}>Submit review</Text>}</Pressable></View></View>
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:C.midnight},header:{height:64,flexDirection:"row",alignItems:"center",justifyContent:"space-between",paddingHorizontal:18,borderBottomWidth:1,borderBottomColor:C.border},icon:{width:42,height:42,borderRadius:21,alignItems:"center",justifyContent:"center",backgroundColor:C.royalNavy},title:{color:C.white,fontSize:19,fontWeight:"900"},content:{padding:20},eye:{color:C.gold,fontSize:9,fontWeight:"900",letterSpacing:1.5},head:{color:C.white,fontSize:23,fontWeight:"900",marginTop:8},stars:{flexDirection:"row",gap:10,marginTop:25},input:{minHeight:160,borderRadius:20,borderWidth:1,borderColor:C.border,backgroundColor:C.input,color:C.white,padding:16,textAlignVertical:"top",fontSize:12,lineHeight:19,marginTop:25},count:{color:C.muted,fontSize:9,textAlign:"right",marginTop:6},cta:{height:54,borderRadius:17,backgroundColor:C.gold,alignItems:"center",justifyContent:"center",marginTop:18},ctaText:{color:C.midnight,fontSize:12,fontWeight:"900"}});
