import React,{useCallback,useEffect,useState} from "react";
import {ActivityIndicator,Pressable,RefreshControl,ScrollView,StyleSheet,Text,View} from "react-native";
import {ArrowLeft,Bookmark,ChevronRight} from "lucide-react-native";
import {endpoints,errMsg,listOf} from "../api";
import {OMIQORA} from "../theme";
const C=OMIQORA.colors;
export function SavedScreen({onBack,onOpen}:{onBack:()=>void;onOpen:(id:string)=>void}){
 const [items,setItems]=useState<any[]>([]),[busy,setBusy]=useState(true),[error,setError]=useState("");
 const load=useCallback(async()=>{setError("");try{setItems(listOf(await endpoints.saved()))}catch(e){setError(errMsg(e))}finally{setBusy(false)}},[]);
 useEffect(()=>{load()},[load]);
 return <View style={s.page}><View style={s.header}><Pressable onPress={onBack} style={s.icon}><ArrowLeft size={20} color={C.gold}/></Pressable><Text style={s.title}>Saved services</Text><View style={s.icon}/></View>{busy?<View style={s.center}><ActivityIndicator color={C.gold}/></View>:<ScrollView contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={busy} onRefresh={()=>{setBusy(true);load()}} tintColor={C.gold}/>}><Text style={s.eye}>YOUR COLLECTION</Text>{error?<Text style={s.error}>{error}</Text>:null}{!items.length&&!error?<View style={s.empty}><Bookmark size={30} color={C.gold}/><Text style={s.emptyTitle}>Nothing saved yet</Text><Text style={s.muted}>Save services you want to compare or book later.</Text></View>:items.map(item=>{const id=String(item?._id??item?.id??"");return <Pressable key={id} style={s.card} onPress={()=>id&&onOpen(id)}><View style={{flex:1}}><Text style={s.name}>{item?.name??"OMIQORA service"}</Text><Text style={s.meta}>₹{Number(item?.basePrice??0).toLocaleString("en-IN")} · {item?.location?.city??"Location varies"}</Text></View><ChevronRight size={18} color={C.gold}/></Pressable>})}</ScrollView>}</View>
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:C.midnight},header:{height:64,flexDirection:"row",alignItems:"center",justifyContent:"space-between",paddingHorizontal:18,borderBottomWidth:1,borderBottomColor:C.border},icon:{width:42,height:42,borderRadius:21,alignItems:"center",justifyContent:"center",backgroundColor:C.royalNavy},title:{color:C.white,fontSize:19,fontWeight:"900"},content:{padding:20,paddingBottom:40},eye:{color:C.gold,fontSize:9,fontWeight:"900",letterSpacing:1.5,marginBottom:12},center:{flex:1,alignItems:"center",justifyContent:"center"},empty:{minHeight:280,alignItems:"center",justifyContent:"center",padding:30},emptyTitle:{color:C.white,fontSize:15,fontWeight:"900",marginTop:12},muted:{color:C.muted,fontSize:10,lineHeight:17,textAlign:"center",marginTop:7},error:{color:C.danger,fontSize:11,marginBottom:12},card:{minHeight:78,borderRadius:18,borderWidth:1,borderColor:C.border,backgroundColor:C.royalNavy,padding:15,marginBottom:10,flexDirection:"row",alignItems:"center"},name:{color:C.white,fontSize:13,fontWeight:"900"},meta:{color:C.muted,fontSize:10,marginTop:6}});
