import React,{useCallback,useEffect,useState} from "react";
import * as DocumentPicker from "expo-document-picker";
import * as Location from "expo-location";
import {ActivityIndicator,Alert,Pressable,ScrollView,StyleSheet,Text,TextInput,View} from "react-native";
import {ArrowLeft,BriefcaseBusiness,FileCheck2,MapPin,RefreshCw,Upload} from "lucide-react-native";
import {api,endpoints,errMsg,listOf,unwrap} from "../api";
import {useSession} from "../stores/session";
import {OMIQORA} from "../theme";
const C=OMIQORA.colors;
const F=({label,value,setValue,secure=false}:{label:string;value:string;setValue:(v:string)=>void;secure?:boolean})=><TextInput style={s.field} placeholder={label} placeholderTextColor={C.mutedSoft} value={value} onChangeText={setValue} secureTextEntry={secure}/>;
export function VendorScreen({onBack}:{onBack:()=>void}){
 const user=useSession(x=>x.user),[overview,setOverview]=useState<any>(null),[services,setServices]=useState<any[]>([]),[application,setApplication]=useState<any>(null),[busy,setBusy]=useState(true),[error,setError]=useState("");
 const[businessName,setBusinessName]=useState(""),[description,setDescription]=useState(""),[city,setCity]=useState(""),[state,setState]=useState(""),[address,setAddress]=useState(""),[businessPhone,setBusinessPhone]=useState("");
 const[panNumber,setPanNumber]=useState(""),[accountName,setAccountName]=useState(""),[accountNumber,setAccountNumber]=useState(""),[ifscCode,setIfscCode]=useState(""),[bankName,setBankName]=useState(""),[portfolio,setPortfolio]=useState("");
 const load=useCallback(async()=>{setBusy(true);setError("");try{if(user?.role==="vendor"||user?.isVendorApproved){const[o,sv]=await Promise.all([endpoints.vendorOverview(),endpoints.myServices()]);setOverview(unwrap(o));setServices(listOf(sv));}else{setApplication(unwrap(await endpoints.vendorApplication()));}}catch(e:any){if(e?.response?.status===404)setApplication(null);else setError(errMsg(e));}finally{setBusy(false);}},[user]);
 useEffect(()=>{load()},[load]);
 const locate=async()=>{const p=await Location.requestForegroundPermissionsAsync();if(p.status!=="granted")return Alert.alert("Location","Permission is required.");const pos=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.High});const a=(await Location.reverseGeocodeAsync(pos.coords))[0];setCity(a?.city??a?.district??"");setState(a?.region??"");setAddress([a?.name,a?.street,a?.district,a?.city,a?.region,a?.postalCode].filter(Boolean).join(", "));return {latitude:pos.coords.latitude,longitude:pos.coords.longitude};};
 const apply=async()=>{try{setBusy(true);const point=await locate();const data:any=unwrap(await endpoints.applyVendor({businessName,businessDescription:description,categories:["general"],city,state,address,businessPhone,panNumber,portfolioLinks:portfolio.split(",").map(x=>x.trim()).filter(Boolean),bankDetails:{accountName,accountNumber,ifscCode,bankName},serviceLocation:{formattedAddress:address,city,state,latitude:point?.latitude,longitude:point?.longitude,serviceRadiusKm:25}}));setApplication(data);Alert.alert("Vendor application submitted","Upload Aadhaar or PAN and work proof next.");}catch(e){Alert.alert("Application failed",errMsg(e));}finally{setBusy(false);}};
 const upload=async(type:string)=>{try{const pick=await DocumentPicker.getDocumentAsync({type:["image/jpeg","image/png","image/webp","application/pdf"],copyToCacheDirectory:true});if(pick.canceled)return;const asset=pick.assets[0];const form=new FormData();form.append("type",type);form.append("file",{uri:asset.uri,name:asset.name,mimeType:asset.mimeType,type:asset.mimeType} as any);await api.post("/vendor-applications/upload-document",form,{headers:{"Content-Type":"multipart/form-data"}});Alert.alert("Uploaded",`${type.replace("_"," ")} submitted for review.`);await load();}catch(e){Alert.alert("Upload failed",errMsg(e));}};
 if(busy)return <View style={s.center}><ActivityIndicator color={C.gold}/></View>;
 return <ScrollView style={s.page} contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><View style={s.header}><Pressable onPress={onBack}><ArrowLeft size={20} color={C.goldLight}/></Pressable><Text style={s.title}>Vendor verification</Text></View>
 {error?<><Text style={s.error}>{error}</Text><Pressable onPress={load} style={s.cta}><RefreshCw size={16}/><Text>Retry</Text></Pressable></>:user?.role==="vendor"||user?.isVendorApproved?<><View style={s.hero}><BriefcaseBusiness size={25} color={C.goldLight}/><Text style={s.heroTitle}>Verified vendor workspace</Text></View><Text style={s.section}>OVERVIEW</Text>{Object.entries(overview??{}).filter(([,v])=>typeof v==="number").slice(0,6).map(([k,v])=><Text style={s.copy} key={k}>{k}: {String(v)}</Text>)}<Text style={s.section}>MY SERVICES</Text>{services.map((x,i)=><Text style={s.copy} key={String(x?._id??i)}>{x?.name} Â· {x?.status}</Text>)}</>:application?<><View style={s.hero}><FileCheck2 size={25} color={C.goldLight}/><Text style={s.heroTitle}>Application: {application.status}</Text><Text style={s.copy}>KYC documents are reviewed by OMIQORA admins. Sensitive bank details are not returned by the API.</Text></View><Text style={s.section}>IDENTITY & BUSINESS PROOFS</Text>{["aadhaar","pan","business_license","profile_photo","shop_photo","portfolio","work_proof"].map(t=><Pressable key={t} style={s.upload} onPress={()=>upload(t)}><Upload size={17} color={C.goldLight}/><Text style={s.uploadText}>Upload {t.replaceAll("_"," ")}</Text></Pressable>)}</>:<><View style={s.hero}><MapPin size={25} color={C.goldLight}/><Text style={s.heroTitle}>Real vendor onboarding</Text><Text style={s.copy}>Business identity, bank, address, location and proof details are submitted to the live API.</Text></View>
 <F label="Business / individual name" value={businessName} setValue={setBusinessName}/><F label="Business description (20+ characters)" value={description} setValue={setDescription}/><F label="Business phone (+91...)" value={businessPhone} setValue={setBusinessPhone}/><F label="PAN number" value={panNumber} setValue={setPanNumber}/><F label="City" value={city} setValue={setCity}/><F label="State" value={state} setValue={setState}/><F label="Full address" value={address} setValue={setAddress}/><F label="Portfolio links, comma separated" value={portfolio} setValue={setPortfolio}/>
 <Text style={s.section}>BANK / PAYOUT DETAILS</Text><F label="Account holder name" value={accountName} setValue={setAccountName}/><F label="Account number" value={accountNumber} setValue={setAccountNumber} secure/><F label="IFSC code" value={ifscCode} setValue={setIfscCode}/><F label="Bank name" value={bankName} setValue={setBankName}/>
 <Pressable style={s.cta} onPress={apply}><Text style={s.ctaText}>Use location & submit application</Text></Pressable></>}</ScrollView>;
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:C.midnight},content:{padding:20,paddingBottom:70},center:{flex:1,backgroundColor:C.midnight,alignItems:"center",justifyContent:"center"},header:{height:60,flexDirection:"row",alignItems:"center",gap:16},title:{color:C.white,fontSize:22,fontWeight:"800"},hero:{padding:20,borderRadius:22,backgroundColor:C.deepNavy,marginVertical:16},heroTitle:{color:C.white,fontSize:20,fontWeight:"800",marginTop:10},copy:{color:C.muted,lineHeight:22,marginTop:8},section:{color:C.goldLight,fontWeight:"800",letterSpacing:1.4,marginTop:22,marginBottom:10},field:{minHeight:56,borderWidth:1,borderColor:C.border,borderRadius:16,color:C.white,paddingHorizontal:16,marginBottom:12},upload:{minHeight:52,borderWidth:1,borderColor:C.border,borderRadius:16,flexDirection:"row",alignItems:"center",gap:10,paddingHorizontal:16,marginBottom:10},uploadText:{color:C.white,textTransform:"capitalize"},cta:{minHeight:58,borderRadius:18,backgroundColor:C.goldLight,alignItems:"center",justifyContent:"center",flexDirection:"row",gap:8,marginTop:18},ctaText:{color:C.midnight,fontWeight:"800"},error:{color:"#ff9b9b"}});
