import React,{useCallback,useEffect,useState} from "react";
import {ActivityIndicator,Pressable,ScrollView,StyleSheet,Text,View} from "react-native";
import {ArrowLeft,BriefcaseBusiness,RefreshCw,Sparkles} from "lucide-react-native";
import {endpoints,errMsg,listOf,unwrap} from "../api";
import {useSession} from "../stores/session";
import {OMIQORA} from "../theme";
const C=OMIQORA.colors;
export function VendorScreen({onBack}:{onBack:()=>void}){
 const user=useSession(x=>x.user);const [overview,setOverview]=useState<any>(null),[services,setServices]=useState<any[]>([]),[application,setApplication]=useState<any>(null),[busy,setBusy]=useState(true),[error,setError]=useState("");
 const load=useCallback(async()=>{setBusy(true);setError("");try{if(user?.role==="vendor"||user?.isVendorApproved){const [o,sv]=await Promise.all([endpoints.vendorOverview(),endpoints.myServices()]);setOverview(unwrap(o));setServices(listOf(sv))}else{try{setApplication(unwrap(await endpoints.vendorApplication()))}catch{setApplication(null)}}}catch(e){setError(errMsg(e))}finally{setBusy(false)}},[user]);
 useEffect(()=>{load()},[load]);
 return <ScrollView style={s.page} contentContainerStyle={s.content}><View style={s.header}><Pressable onPress={onBack} style={s.icon}><ArrowLeft size={20} color={C.goldLight}/></Pressable><View><Text style={s.eye}>OMIQORA PARTNERS</Text><Text style={s.title}>Vendor space</Text></View></View>
 {busy?<View style={s.center}><ActivityIndicator color={C.gold}/></View>:error?<View style={s.center}><Text style={s.error}>{error}</Text><Pressable onPress={load} style={s.retry}><RefreshCw size={16} color={C.midnight}/><Text style={s.retryText}>Retry</Text></Pressable></View>:user?.role==="vendor"||user?.isVendorApproved?<><View style={s.hero}><BriefcaseBusiness size={25} color={C.goldLight}/><Text style={s.heroTitle}>Your live vendor workspace</Text><Text style={s.copy}>This mobile view reads your real OMIQORA vendor analytics and services.</Text></View><Text style={s.section}>OVERVIEW</Text><View style={s.grid}>{Object.entries(overview??{}).filter(([,v])=>typeof v==="number").slice(0,6).map(([k,v])=><View style={s.metric} key={k}><Text style={s.value}>{String(v)}</Text><Text style={s.label}>{k.replace(/([A-Z])/g," $1")}</Text></View>)}</View><Text style={s.section}>MY SERVICES</Text>{services.length?services.map((x,i)=><View style={s.card} key={String(x?._id??i)}><Text style={s.cardTitle}>{x?.name??x?.title??"Service"}</Text><Text style={s.copy}>{x?.status??"Live service record"}</Text></View>):<Text style={s.copy}>No services returned by your vendor account.</Text>}</>:<View style={s.hero}><Sparkles size={26} color={C.goldLight}/><Text style={s.heroTitle}>Grow with OMIQORA</Text><Text style={s.copy}>{application?`Application status: ${application?.status??"submitted"}`:"No vendor application is linked to this account yet. Vendor application creation remains on the OMIQORA web workflow until the document-upload contract is moved to native mobile."}</Text></View>}
 </ScrollView>
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:C.midnight},content:{padding:18,paddingBottom:35},header:{flexDirection:"row",alignItems:"center",gap:12},icon:{width:42,height:42,borderRadius:14,borderWidth:1,borderColor:C.border,backgroundColor:C.royalNavy,alignItems:"center",justifyContent:"center"},eye:{color:C.gold,fontSize:8,fontWeight:"900",letterSpacing:1.5},title:{color:C.white,fontSize:22,fontWeight:"900",marginTop:3},center:{minHeight:350,alignItems:"center",justifyContent:"center"},hero:{marginTop:22,borderRadius:24,borderWidth:1,borderColor:C.borderStrong,backgroundColor:C.royalNavy,padding:20},heroTitle:{color:C.white,fontSize:18,fontWeight:"900",marginTop:14},copy:{color:C.muted,fontSize:10,lineHeight:17,marginTop:7},section:{color:C.gold,fontSize:8,fontWeight:"900",letterSpacing:1.5,marginTop:24,marginBottom:10},grid:{flexDirection:"row",flexWrap:"wrap",gap:9},metric:{width:"48%",borderRadius:17,borderWidth:1,borderColor:C.border,backgroundColor:C.elevatedNavy,padding:14},value:{color:C.goldLight,fontSize:19,fontWeight:"900"},label:{color:C.muted,fontSize:9,marginTop:5,textTransform:"capitalize"},card:{borderRadius:17,borderWidth:1,borderColor:C.border,backgroundColor:C.royalNavy,padding:14,marginBottom:8},cardTitle:{color:C.white,fontSize:12,fontWeight:"900"},error:{color:C.danger,textAlign:"center",fontSize:12},retry:{marginTop:14,height:43,borderRadius:14,backgroundColor:C.gold,paddingHorizontal:16,flexDirection:"row",alignItems:"center",gap:7},retryText:{color:C.midnight,fontWeight:"900",fontSize:11}});
